/*
 * tmp102.h
 *
 *  Created on: Jul 16, 2022
 *      Author: hg26972
 */

#ifndef INC_TMP102_H_
#define INC_TMP102_H_

#include "main.h"

#define TMP102_I2C_PORT hi2c1 	// I2C port as defined in main generated by CubeMx
#define TMP102_UART_PORT huart2  // UART port defined in main for debug

/* CODE BEGIN External variables */
//	Definition of the i2c port in main
extern I2C_HandleTypeDef TMP102_I2C_PORT;
//	Definition of the uart port in main
extern UART_HandleTypeDef TMP102_UART_PORT;


void tmp102_ReadTemperature(uint8_t* tempText);
#endif /* INC_TMP102_H_ */
